### ISSUE TITLE
Support Qt5

### ISSUE THREAD

**Issue by mchamberland** [MartinMartinov/3ddose_tools#1]
Qt4 is getting long in the tooth. All EGSnrc GUIs have been updated to support Qt5. It would be nice to have support for Qt5 in 3ddose_tools.

**Comment by mchamberland** [comment]
It seems like it should be fairly straightforward. Mostly replacing \<QtGui\> with \<QtWidgets\> and adding QT += widgets in the *.pro file. It compiles fine with those changes, but no window appears when I launch the application... (but that might just be a problem with my system)

**Comment by MartinMartinov** [comment]
I do have a Qt5 version kicking around somewhere I use on Windows.  You're right, it's been long enough, I will be updating the code soon.

**Comment by MartinMartinov** [comment]
Took some time to get Qt5 working on our old scientific linux distribution, but we finally got it working.  The code should compile on Qt5 no problem.
