### ISSUE TITLE
Installation instructions are incomplete

### ISSUE THREAD

**Issue by rtownson** [MartinMartinov/3ddose_tools#3]
In the documentation PDF it says there is an installation script, but I don't see one. I suggest you update the docs to include `cd source; qmake; make` as one way of installing, and include the installer script in the repo if it is also useful.

**Comment by MartinMartinov** [comment]
I honestly completely forgot about the documentation.  Most of it is outdated and might not be accurate to most of the functions now.  I think I'll leave it in but rename the folder to legacy-beta-documentation, at least until I update the README to be a comprehensive description of functions (at some point).

**Comment by MartinMartinov** [comment]
Changed the README, finally -_-
