### ISSUE TITLE
egsphant preview not working

### ISSUE THREAD

**Issue by rtownson** [MartinMartinov/3ddose_tools#4]
I've tried compiling with Qt 5.10.1 and it does so fine. When I load the application it launches, loads 3ddose files and produces plots. When I load an egsphant file, it seems to read in and display the boundaries, but nothing appears in the visualization area.

**Comment by MartinMartinov** [comment]
Could you share the egsphant in question with me?  I'd need to take a look at what's happening.

**Comment by rtownson** [comment]
So far I haven't been able to load any egsphant file at all! I've tried about 6 different and checked that they open in dosxyz_show. I can email you one. I'm on linux. 

![image](https://user-images.githubusercontent.com/13069227/181254111-11e1fab4-f72a-4e93-b198-be38027256a4.png)

**Comment by MartinMartinov** [comment]
Before I start digging too deep, have you tried viewing it while one of the dose distribution options below were selected?
![image](https://user-images.githubusercontent.com/15231799/181394353-20d79ec4-6f34-465d-87b2-e723cdaeac3c.png)
I know it's super non-intuitive, and the program should be able to just draw the blank canvas when no dose is selected, but the architecture is pretty hodge-podge (you should see the much better stuff I do in https://github.com/clrp-code/eb_gui) and crashed every time I tried it.

**Comment by rtownson** [comment]
Yep, that was the problem! I didn't know those options needed to be changed.

**Comment by MartinMartinov** [comment]
Yeah, it's a hold-over from a pre-egsphant implementation, and it was surprisingly tricky to circumvent.  The two should really be independent.  I'll close this issue for now, but I'll be sure to fix the previewer next time I get a big break.  Our at least make it clear you need to load dose as well if it's a short break :)
