### ISSUE TITLE
How can I find install script and how to install

### ISSUE THREAD

**Issue by tairozero** [MartinMartinov/3ddose_tools#5]
Dear prof. Martin

I'm interest in your 3ddose_tool. Anyway, I can't  find the install-script that your mention in the user guide. Can you tell me where can I find it and how to install this program?

Thank you

**Comment by MartinMartinov** [comment]
I modified https://github.com/MartinMartinov/3ddose_tools/blob/master/README.md to give better and more complete instructions.  Hopefully, the installing from scratch guide helps.  I just installed it now with those commands on a brand new Linux box, and I got it to run.
